package com.example.bm77_bc_code;

import java.io.Serializable;
import u.aly.bs;

public class BC401_Struct_All implements Serializable {
    private static final long serialVersionUID = 1;
    public byte BIL = 0;
    public byte BIL1 = 0;
    public String BIL_Real = bs.b;
    public byte BLD = 0;
    public byte BLD1 = 0;
    public String BLD_Real = bs.b;
    public byte CR = 0;
    public byte CR1 = 0;
    public String CR_Real = bs.b;
    public int Date = 0;
    public byte GLU = 0;
    public byte GLU1 = 0;
    public String GLU_Real = bs.b;
    public int Hour = 0;
    public int ID = 0;
    public int Item = 0;
    public byte KET = 0;
    public byte KET1 = 0;
    public String KET_Real = bs.b;
    public byte LEU = 0;
    public byte LEU1 = 0;
    public String LEU_Real = bs.b;
    public byte MAL = 0;
    public byte MAL1 = 0;
    public String MAL_Real = bs.b;
    public int Min = 0;
    public int Month = 0;
    public byte NIT = 0;
    public byte NIT1 = 0;
    public String NIT_Real = bs.b;
    public byte PH = 0;
    public byte PH1 = 0;
    public String PH_Real = bs.b;
    public byte PRO = 0;
    public byte PRO1 = 0;
    public String PRO_Real = bs.b;
    public byte SG = 0;
    public byte SG1 = 0;
    public String SG_Real = bs.b;
    public int Sec = 0;
    public byte UCA = 0;
    public byte UCA1 = 0;
    public String UCA_Real = bs.b;
    public byte URO = 0;
    public byte URO1 = 0;
    public String URO_Real = bs.b;
    public int User = 0;
    public byte VC = 0;
    public byte VC1 = 0;
    public String VC_Real = bs.b;
    public int Year = 0;
}
